# Fancy Index
- Bir liste içine bu arrayden istediğimiz indislerini koyarak o indislerdeki verileri alabiliriz.

In [3]:
import numpy as np

In [4]:
v = np.arange(0, 30, 3)
print(v)


[ 0  3  6  9 12 15 18 21 24 27]


In [6]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [7]:
getir = [1, 3, 5]
print(v[getir])

[ 3  9 15]


In [8]:
m = np.arange(9).reshape(3, 3)
satir = np.array([0, 1])
sutun = np.array([1, 2])
print(m[satir, sutun])

[1 5]


In [9]:
print(m[0, [1, 2]])

[1 2]


In [10]:
m[0:, [1, 2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [13]:
v = np.array([1, 2, 3, 4, 5])
print(v > 3)

[False False False  True  True]


In [14]:
print(v[v > 3])

[4 5]


In [15]:
print(v[v < 3])

[1 2]


In [16]:
print(v[v >= 3])

[3 4 5]


In [17]:
print(v[v <= 3])

[1 2 3]


In [18]:
print(v[v != 3])

[1 2 4 5]


In [19]:
print(v[v == 3])

[3]


# Matematiksel İşlemler

In [20]:
print(v * 2)

[ 2  4  6  8 10]


In [21]:
print(v + 2)

[3 4 5 6 7]


In [23]:
print(v * 5 / 10)

[0.5 1.  1.5 2.  2.5]


In [24]:
print(v ** 2)

[ 1  4  9 16 25]


In [25]:
print(np.subtract(v, 2)) # .subtract() fonksiyonu vektörlerde çıkarma işlemi yapar.

[-1  0  1  2  3]


In [26]:
print(np.add(v, 2)) # .add() fonksiyonu vektörlerde toplama işlemi yapar.

[3 4 5 6 7]


In [27]:
print(np.multiply(v, 2)) # .multiply() fonksiyonu vektörlerde çarpma işlemi yapar.

[ 2  4  6  8 10]


In [28]:
print(np.divide(v, 2)) #.divide()  fonksiyonu vektörlerde bölme işlemi yapar.

[0.5 1.  1.5 2.  2.5]


In [29]:
print(np.power(v, 2)) # .power() fonksiyonu vektörlerde üs alma işlemi yapar.

[ 1  4  9 16 25]


In [30]:
print(np.mod(v, 2)) # .mod() fonksiyonu vektörlerde mod alma işlemi yapar.

[1 0 1 0 1]


In [32]:
print(np.absolute(v)) # .absolute() fonksiyonu vektörlerde mutlak değer alma işlemi yapar.

[1 2 3 4 5]


In [33]:
print(np.sin(360)) # .sin() fonksiyonu vektörlerde sinüs alma işlemi yapar.

0.9589157234143065


In [34]:
np.cos(360) # .cos() fonksiyonu vektörlerde kosinüs alma işlemi yapar.

-0.2836910914865273

In [35]:
print(np.log(10)) # .log() fonksiyonu vektörlerde logaritma alma işlemi yapar.

2.302585092994046


In [36]:
print(np.log(v))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [37]:
print(np.log10(v))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [38]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\BERKCAN\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\berkcan\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippe