In [1]:
import numpy as np

**np.arange()**
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.arange(start, stop, step)

In [3]:
result = np.arange(1, 10)
print(result)

[1 2 3 4 5 6 7 8 9]


**np.zeros()**
- 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [4]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**np.ones()**
- 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [5]:
one = np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**np.linspace()**
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.linspace(başlangıç, bitiş, bölünecek aralık)

In [6]:
lins = np.linspace(0, 100, 5)
print(lins)

[  0.  25.  50.  75. 100.]


In [9]:
result = np.random.randint(0, 10,3)
print(result)

[4 2 0]


In [10]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis = 1))
print(npMulti.sum(axis = 0))

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


# Numpy Array'in Özellikleri 
- ndim : Boyut sayısı
- shape : Boyut bilgisi
- size : Toplam Eleman sayısı
- dtype : Veri tipi

In [11]:
a = np.random.randint(10, size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


In [13]:
b = np.random.randint(10, size = (3,5))
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

2
(3, 5)
15
int32
