# Array Sıralama(Sorting)
* Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan **sort()** fonksiyonu kullanılır.

In [2]:
import numpy as np

In [3]:
v = np.array([2,1,4,3,5])
print(v)
print(np.sort(v))

[2 1 4 3 5]
[1 2 3 4 5]


In [4]:
v.sort()
print(v)

[1 2 3 4 5]


In [5]:
m = np.random.normal(20,5,(3,3))
print(m)

[[18.28865965 14.85028842 15.10460525]
 [19.66093972 22.29786837 23.96474286]
 [23.41707741 13.24068725 19.65079455]]


In [6]:
print(np.sort(m, axis=0))

[[18.28865965 13.24068725 15.10460525]
 [19.66093972 14.85028842 19.65079455]
 [23.41707741 22.29786837 23.96474286]]


In [7]:
print(np.sort(m, axis=1))

[[14.85028842 15.10460525 18.28865965]
 [19.66093972 22.29786837 23.96474286]
 [13.24068725 19.65079455 23.41707741]]


# Index ile Elemanlara Erişmek

In [8]:
a = np.random.randint(10,size = 10)
print(a)

[2 7 0 2 1 5 4 6 7 5]


In [9]:
print(a[0])

2


In [10]:
print(a[-1])

5


In [11]:
a[0] = 100
print(a)

[100   7   0   2   1   5   4   6   7   5]


In [12]:
x = np.random.randint(10,size = (3,5))
print(x)

[[5 0 5 1 0]
 [9 4 1 2 7]
 [3 2 2 7 1]]


In [13]:
print(x[0,0])

5


In [14]:
print(x[1,1])

4


In [15]:
print(x[2,4])

1


In [16]:
x[1,4] = 100
print(x)

[[  5   0   5   1   0]
 [  9   4   1   2 100]
 [  3   2   2   7   1]]


In [17]:
x[1,4] = 3.14
print(x)

[[5 0 5 1 0]
 [9 4 1 2 3]
 [3 2 2 7 1]]


# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [18]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [19]:
print(a[0:3])

[20 21 22]


In [20]:
print(a[:3])

[20 21 22]


In [21]:
print(a[3:])

[23 24 25 26 27 28 29]


In [22]:
print(a[1::2]) # 1 den başla ikişer atla

[21 23 25 27 29]


In [23]:
print(a[0::2])

[20 22 24 26 28]


In [24]:
print(a[2::2])

[22 24 26 28]


In [25]:
print(a[1::3])

[21 24 27]


In [27]:
b = np.random.randint(10,size = (5,5))
print(b)

[[5 7 5 0 3]
 [0 2 0 7 3]
 [6 5 3 4 9]
 [7 1 0 5 6]
 [7 4 1 1 1]]


In [28]:
print(b[:,0]) # tüm satırların sıfırıncı sütunlarındaki elemanları al

[5 0 6 7 7]


In [29]:
print(b[:,1]) # tüm satırların birinci sütunlarındaki elemanları al 

[7 2 5 1 4]


In [30]:
print(b[0,:]) # tüm sütunların sıfırıncı satırlarındaki elemanları al

[5 7 5 0 3]


In [31]:
print(b[1,:]) # tüm sütunların birinci satırlarındaki elemanları al

[0 2 0 7 3]


In [32]:
print(b[0:2,0:3]) # 0 ve 1. satırların 0,1,2. sütunlarındaki elemanları al

[[5 7 5]
 [0 2 0]]


In [33]:
print(b[::2,::2]) # 2şer 2şer atla

[[5 5 3]
 [6 3 9]
 [7 1 1]]


# Alt Küme Üzerinde İşlem Yapmak

In [35]:
alt_b = b[0:3, 0:2]
alt_b

array([[5, 7],
       [0, 2],
       [6, 5]])

In [36]:
alt_b[0,0] = 100
alt_b[1,1] = 200
print(alt_b)

[[100   7]
 [  0 200]
 [  6   5]]


In [37]:
print(b)

[[100   7   5   0   3]
 [  0 200   0   7   3]
 [  6   5   3   4   9]
 [  7   1   0   5   6]
 [  7   4   1   1   1]]
