# Numpy
- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayar kurmak için ```pip insall numpy``` komutu ile kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

# Neden Numpy?

In [3]:
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [4]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() : Matrisi yeniden boyutlandırır.

In [8]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape : Matrisin boyutlarını verir.    

In [10]:
print(multi.shape)

(3, 3)


In [11]:
print(x.shape)

(9,)


ndim : Matrisin boyutu sayısını verir.  

In [12]:
print(x.ndim)

1


In [13]:
print(multi.ndim)

2
